---
- name: download drill...
  environment: proxy_env
  get_url: url='{{ drill_url }}' dest='/tmp/{{ drill_archive }}'

- name: unarchive dril...
  unarchive: copy=no src='/tmp/{{ drill_archive }}' dest='/opt'

- name: link /opt/drill
  file: src='/opt/{{ drill_name }}' dest='/opt/drill' state=link

- name: include drill in the default path...
  copy: >
    src=etc/profile.d/drill.sh
    dest=/etc/profile.d/pig.sh
    mode=644
    owner=root
    group=root