---
- name: checking for install in {{ drill_install_dir }}
  become: yes
  stat:
    path: '{{ drill_install_dir }}'
  changed_when: False
  register: drill_binary
- when: not drill_binary.stat.exists
  block:
    - name: downloading {{ drill_url }}
      become: yes
      become_user: root
      get_url:
        url: '{{ drill_url }}'
        dest: '{{ drill_tmp_tgz }}'
        checksum: '{{ drill_checksum }}'

    - name: unarchiving {{ drill_tmp_tgz }} to {{ drill_install_parent_dir }}
      become: yes
      become_user: root
      unarchive:
        remote_src: yes
        src: '{{ drill_tmp_tgz }}'
        dest: '{{ drill_install_parent_dir }}'
        creates: '{{ drill_install_dir }}'
  always:
    - name: rm -f {{ drill_tmp_tgz }}
      become: yes
      become_user: root
      file:
        path: '{{ drill_tmp_tgz }}'
        state: absent

- name: linking {{ drill_install_dir }} from {{ drill_link_dir }}
  become: yes
  become_user: root
  file:
    src: '{{ drill_install_dir }}'
    dest: '{{ drill_link_dir }}'
    state: link

- name: include drill in the default shell path...
  become: yes
  become_user: root
  with_items:
    - f: drill.sh
      d: /etc/profile.d
      m: '0644'
  template:
    src: '{{ item.f }}.j2'
    dest: '{{ item.d }}/{{ item.f }}'
    mode: '{{ item.m }}'
