---
- name: Installing andrewrothstein.unarchivedeps
  ansible.builtin.include_role:
    name: andrewrothstein.unarchivedeps
- name: Installing andrewrothstein.temurin
  ansible.builtin.include_role:
    name: andrewrothstein.temurin
  vars:
    openjdk_app: jre
- name: Checking for install in {{ drill_install_dir }}
  become: true
  ansible.builtin.stat:
    path: '{{ drill_install_dir }}'
  changed_when: false
  register: drill_binary
- name: Downloading apache drill
  when: not drill_binary.stat.exists
  block:
    - name: Downloading {{ drill_url }}
      become: true
      become_user: root
      ansible.builtin.get_url:
        url: '{{ drill_url }}'
        dest: '{{ drill_tmp_tgz }}'
        checksum: '{{ drill_checksum }}'
        mode: '644'

    - name: Unarchiving {{ drill_tmp_tgz }} to {{ drill_install_parent_dir }}
      become: true
      become_user: root
      ansible.builtin.unarchive:
        remote_src: true
        src: '{{ drill_tmp_tgz }}'
        dest: '{{ drill_install_parent_dir }}'
        creates: '{{ drill_install_dir }}'
  always:
    - name: Rm -f {{ drill_tmp_tgz }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ drill_tmp_tgz }}'
        state: absent

- name: Linking {{ drill_install_dir }} from {{ drill_link_dir }}
  become: true
  become_user: root
  ansible.builtin.file:
    src: '{{ drill_install_dir }}'
    dest: '{{ drill_link_dir }}'
    state: link

- name: Include drill in the default shell path...
  become: true
  become_user: root
  with_items:
    - f: drill.sh
      d: /etc/profile.d
  ansible.builtin.template:
    src: '{{ item.f }}.j2'
    dest: '{{ item.d }}/{{ item.f }}'
    mode: '{{ item.m | default("644") }}'
